<?php declare(strict_types = 1);

use OriNette\Application\ApplicationMap\ApplicationMap;
use Tracy\Helpers;

/** @var ApplicationMap $map */

?>
<h1>Application map</h1>

<div class="tracy-inner">
	<table style="width: 100%;">
		<thead>
		<tr>
			<th>Presenter</th>
			<th>Action</th>
		</tr>
		</thead>
		<tbody>
		<?php foreach ($map->getAll() as $presenterMeta): ?>
			<?php $presenter = $presenterMeta->getClass() ?>
			<?php $editUri = Helpers::editorUri((new ReflectionClass($presenter))->getFileName()); ?>
			<?php $actionLinkPairs = $presenterMeta->getActionLinkPairs(); ?>

			<?php if ($actionLinkPairs === []): ?>
				<tr>
					<td colspan="2">
						<a href="<?= $editUri ?>">
							<?= $presenter ?>
						</a>
						<?php if (($mappedName = $presenterMeta->getMappedName()) !== null): ?>
							<br>
							<?= $mappedName ?>
						<?php endif; ?>
					</td>
				</tr>
			<?php else: ?>

				<?php
				$i = 1;
				?>
				<?php foreach ($actionLinkPairs as $action => $link): ?>
					<tr>
						<?php if ($i === 1): ?>
							<td rowspan="<?= count($actionLinkPairs) ?>">
								<a href="<?= $editUri ?>">
									<?= $presenter ?>
								</a>
							</td>
						<?php endif; ?>
						<td>
							<?php if (is_string($link)): ?>
								<a href="<?= $link ?>">
									<?= $action !== '' ? $action : 'default' ?>
								</a>
							<?php else: ?>
								<span <?php if ($link->isRouteMissing()): ?>style="color: #dc2626" <?php endif; ?>>
									<?= $action !== '' ? $action : 'default' ?>
								</span>
							<?php endif; ?>
						</td>
					</tr>
					<?php $i++; ?>
				<?php endforeach; ?>

			<?php endif; ?>

		<?php endforeach; ?>
		</tbody>
	</table>
</div>
